services:
  nexvion-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: nexvion-web:v1.0.0
    container_name: nexvion-web-container
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - nexvion-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
      - /var/cache/nginx:rw
      - /var/run:rw
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:80/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  nexvion-network:
    name: nexvion-network
    driver: bridge
