import os
import json
import logging
import urllib.request
import urllib.error

logger = logging.getLogger("ai_engine")

def analyze_incident_with_ai_or_fallback(incident_id, k8s_state, es_logs, prom_metrics, primary_classification, severity, severity_reason, confidence):
    """
    Analyzes incident evidence using AI Provider if AI_API_KEY is configured,
    or falls back to a deterministic Rule-Based Analysis engine.
    """
    ai_provider = os.getenv("AI_PROVIDER", "google").lower()
    ai_api_key = os.getenv("AI_API_KEY")
    ai_model = os.getenv("AI_MODEL", "gemini-2.5-flash")

    if ai_api_key:
        try:
            logger.info(f"AI_API_KEY detected. Executing AI-Assisted Analysis via {ai_provider} ({ai_model})...")
            ai_result = call_ai_provider(ai_provider, ai_api_key, ai_model, incident_id, k8s_state, es_logs, prom_metrics, primary_classification, severity)
            if ai_result:
                ai_result["analysis_mode"] = "AI-Assisted Analysis"
                ai_result["ai_provider"] = ai_provider
                ai_result["ai_model"] = ai_model
                return ai_result
        except Exception as e:
            logger.warning(f"AI Provider call failed: {e}. Falling back to Rule-Based Analysis.")

    # Rule-Based Fallback
    logger.info("Executing Rule-Based Analysis fallback.")
    return rule_based_analysis(incident_id, k8s_state, es_logs, prom_metrics, primary_classification, severity, severity_reason, confidence)

def rule_based_analysis(incident_id, k8s_state, es_logs, prom_metrics, primary_classification, severity, severity_reason, confidence):
    """Deterministic, rule-based incident analysis fallback."""
    
    # Extract log messages
    logs = [l.get("message", "") for l in es_logs.get("matched_logs", [])]
    combined_logs = "\n".join(logs)
    
    # Extract pod errors
    pod_errors = []
    for p in k8s_state.get("pods", []):
        for c in p.get("containers", []):
            if c.get("waiting_reason"):
                pod_errors.append(f"Pod {p['name']} container {c['name']} waiting: {c['waiting_reason']}")
            if c.get("terminated_reason"):
                pod_errors.append(f"Pod {p['name']} container {c['name']} terminated: {c['terminated_reason']} (Exit Code {c.get('exit_code')})")

    events = [f"{e.get('type')}/{e.get('reason')}: {e.get('message')}" for e in k8s_state.get("events", [])]

    # Formulate Likely Root Cause
    if "NEXVION_AI_INCIDENT_DEMO" in combined_logs or "NEXVION_AI_INCIDENT_DEMO" in incident_id:
        likely_root_cause = "Simulated application fault generated by controlled demonstration workload."
        contributing_factors = [
            "Controlled injection of test log events into pod stdout.",
            "Elasticsearch log collection pipeline validation scenario.",
            "Prometheus & Kubernetes API observability integration test."
        ]
        investigation_steps = [
            "1. Inspect Elasticsearch index `nexvion-logs-*` for demonstration log markers.",
            "2. Verify Kubernetes pod status and container stdout stream logs.",
            "3. Cross-reference Prometheus metrics for pod availability and CPU/memory trends."
        ]
        remediation_steps = [
            "1. Complete automated incident analysis report generation.",
            "2. Clean up temporary demonstration test pod from cluster.",
            "3. Confirm baseline Nexvion platform workloads (`nexvion-web`) remain healthy."
        ]
    elif primary_classification == "CrashLoopBackOff":
        likely_root_cause = f"Container failure causing repeated process crashes: {pod_errors[0] if pod_errors else 'Application runtime crash'}"
        contributing_factors = [
            "Uncaught runtime exception or configuration mismatch in container entrypoint.",
            "Kubernetes kubelet restarting failing container according to pod restartPolicy."
        ]
        investigation_steps = [
            "1. Check container stderr logs using `kubectl logs -n nexvion <pod-name> --previous`.",
            "2. Inspect environment variables and ConfigMap/Secret mounts.",
            "3. Verify memory allocation and CPU limits."
        ]
        remediation_steps = [
            "1. Fix underlying code exception or missing environment variable.",
            "2. Update Deployment manifest with corrected image tag or configuration.",
            "3. Monitor `kubectl rollout status deployment/nexvion-web`."
        ]
    elif primary_classification == "Deployment Failure":
        likely_root_cause = "Insufficient available pod replicas to satisfy Deployment specification."
        contributing_factors = [
            "Pod readiness probe failures or container startup timeouts.",
            "Node capacity or resource limits preventing scheduling."
        ]
        investigation_steps = [
            "1. Run `kubectl describe deployment -n nexvion` to inspect deployment conditions.",
            "2. Check `kubectl get events -n nexvion` for scheduling or probe failure events.",
            "3. Inspect pod logs for startup initialization bottlenecks."
        ]
        remediation_steps = [
            "1. Adjust container resource requests/limits or node capacity.",
            "2. Increase readiness probe `initialDelaySeconds` or `timeoutSeconds` if required.",
            "3. Rollback or re-deploy updated Helm release."
        ]
    elif primary_classification in ["Application Error", "Dependency Failure", "Network/Ingress Issue"]:
        likely_root_cause = f"Evidence suggests {primary_classification.lower()} during request processing."
        contributing_factors = [
            "Upstream endpoint or database connection failure detected in log stream.",
            "Network timeout or HTTP 5xx error response generated by backend component."
        ]
        investigation_steps = [
            "1. Filter Elasticsearch logs by `kubernetes.namespace_name:nexvion` for error stack traces.",
            "2. Test backend endpoint health using internal ClusterIP connectivity.",
            "3. Inspect Ingress controller and Service endpoint routing."
        ]
        remediation_steps = [
            "1. Verify database / upstream service connectivity and credentials.",
            "2. Restart affected backend service pods if connection pool is stuck.",
            "3. Confirm HTTP response status returns 200 OK."
        ]
    else:
        likely_root_cause = "Insufficient evidence to confirm specific root cause; system workloads are operating normally."
        contributing_factors = [
            "No active container failures or critical warning events detected.",
            "All Kubernetes deployment replicas are ready and available."
        ]
        investigation_steps = [
            "1. Continue monitoring cluster metrics via Grafana dashboards.",
            "2. Check Elasticsearch logs for low-severity warnings.",
            "3. Verify HPA autoscaling thresholds."
        ]
        remediation_steps = [
            "1. Maintain routine observability monitoring.",
            "2. Perform periodic log and metric reviews."
        ]

    verification_plan = [
        "1. Run `kubectl get pods -n nexvion` to confirm all pods are 1/1 Ready.",
        "2. Query Elasticsearch via REST API to verify no new error logs are occurring.",
        "3. Confirm Prometheus metrics show `kube_deployment_status_replicas_available == desired`."
    ]

    limitations = [
        "Analysis performed using Rule-Based Analysis fallback engine.",
        "Root cause formulated from empirical heuristics, pod state, Elasticsearch logs, and Prometheus metrics.",
        "Logs rely on ephemeral Elasticsearch staging index."
    ]

    return {
        "analysis_mode": "Rule-Based Analysis",
        "likely_root_cause": likely_root_cause,
        "contributing_factors": contributing_factors,
        "confidence_score": confidence,
        "investigation_steps": investigation_steps,
        "recommended_remediation": remediation_steps,
        "verification_plan": verification_plan,
        "limitations": limitations
    }

def call_ai_provider(provider, api_key, model, incident_id, k8s_state, es_logs, prom_metrics, primary_classification, severity):
    """Makes HTTP API call to configured AI Provider (Gemini / OpenAI compatible API)."""
    # Formulate structured prompt
    prompt = f"""You are an expert Cloud-Native DevOps Incident Analyzer.
Analyze the following Kubernetes incident evidence and output JSON only with fields:
likely_root_cause (str), contributing_factors (list of str), confidence_score (float 0-1),
investigation_steps (list of str), recommended_remediation (list of str), verification_plan (list of str), limitations (list of str).

Incident ID: {incident_id}
Classification: {primary_classification}
Severity: {severity}

Kubernetes State Summary:
{json.dumps(k8s_state.get('summary', {}), indent=2)}

Pods State:
{json.dumps(k8s_state.get('pods', []), indent=2)}

Elasticsearch Logs Summary:
Hits: {es_logs.get('total_hits')}, Errors: {es_logs.get('error_count')}, Warnings: {es_logs.get('warning_count')}
Sample Logs:
{json.dumps([l.get('message') for l in es_logs.get('matched_logs', [])[:5]], indent=2)}

Prometheus Metrics Summary:
{json.dumps(prom_metrics.get('summary', {}), indent=2)}
"""

    if provider in ["google", "gemini"]:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {"responseMimeType": "application/json"}
        }
        req = urllib.request.Request(url, data=json.dumps(payload).encode("utf-8"), headers={"Content-Type": "application/json"})
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            content_str = data["candidates"][0]["content"]["parts"][0]["text"]
            return json.loads(content_str)
            
    elif provider in ["openai", "custom"]:
        url = "https://api.openai.com/v1/chat/completions"
        payload = {
            "model": model,
            "response_format": {"type": "json_object"},
            "messages": [{"role": "system", "content": "You are a DevOps Incident Analysis AI."}, {"role": "user", "content": prompt}]
        }
        req = urllib.request.Request(url, data=json.dumps(payload).encode("utf-8"), headers={"Content-Type": "application/json", "Authorization": f"Bearer {api_key}"})
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            content_str = data["choices"][0]["message"]["content"]
            return json.loads(content_str)

    return None
