apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nexvion-web.fullname" . }}-config
  namespace: {{ .Values.namespace | default "nexvion" }}
  labels:
    {{- include "nexvion-web.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.config.appName | default "nexvion-web" | quote }}
  ENVIRONMENT: {{ .Values.config.environment | default "staging" | quote }}
  PORT: {{ .Values.containerPort | default 80 | quote }}
  HEALTH_CHECK_PATH: {{ .Values.healthCheck.path | default "/healthz" | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | default "info" | quote }}
